### ISSUE TITLE
Hello my Frind i am also a Typescript insider and i am wondering about your solution

### ISSUE THREAD

**Issue by frank-dspeed** [hanseltime/ignore-bad-ts#1]
I looked at this because i am coding tooling for the same problems.

My question: Why did you favor adding // @ ts-nocheck over tsconfig.json "exclude"

my personal opinion at present is that when the tsconfig gets used we would not need additional unexpected files.

**Comment by hanseltime** [comment]
Hey Frank!

That's a great question.  This solution is super niche (and hopefully not needed by most people).  I ran into an issue where I was being asked to import a shared library from a partner organization that had been written using typescript notation but never compiled during CI/CD (and wouldn't compile).  This library was heavily developed, not transpiled on bundling, and was not going to change its typescript issues.

Since I was compiling down to es2015, I had to transpile the library with the rest of my code (including for tree-shaking purposes), as well as did want to lose type-hinting, etc, from the IDE for the project (it was a large library).  This lead to the special use-case of this build script.

I completely agree with you about tsconfig needing to be the only solution, and normally I would agree.

Other ways to solve this problem could involve adding separate transpilation to a temporary folder before your main transpilation.  Part of the hope behind this script is that it's a one-liner most of the time, and it's name is pretty eye-brow raising if you're looking back at your code.

```bash
build": "ignore-bad-ts node_modules/my-company-module/** && tsc"
```

Ideally, a developer can look at this, and say exactly what you're saying.  Then, when they discover that the library still isn't fixed, they can either fix it, raise it for the maintainer, or leave it until they or someone else is bothered enough by running "ignore-bad-ts" to go to the first two options.

I hope that makes sense!

**Comment by frank-dspeed** [comment]
nice knowleg exchange i think your right it was a one time solution and the typescript main project is adding more and more ways to handle that like subprojects and references where we simply could add no check via that sub tsconfig and so on

also npm did add package overrrides so we could add d.ts files without need to inform the upstream maintainer that does not care

Thanks for answering and spending your value able time!
